variable "client_id" {
    default = env("BUILD_CLIENT_ID")
}
variable "client_secret" {
    default = env("BUILD_CLIENT_SECRET")
}
variable "subscription_id" {
    default = env("BUILD_SUBSCRIPTION_ID")
}
variable tenant_id {
    default = env("BUILD_TENANT_ID")
}

source "azure-arm" "autogenerated_1" {
  azure_tags = {
    dept = "Engineering"
    task = "Image deployment"
  }
  client_id                         = "${var.client_id}"
  client_secret                     = "${var.client_secret}"
  image_offer                       = "0001-com-ubuntu-server-jammy"
  image_publisher                   = "canonical"
  image_sku                         = "22_04-lts"
  location                          = "West Europe"
  managed_image_name                = "nestedKVMImage"
  managed_image_resource_group_name = "ImageBuildRG"
  os_type                           = "Linux"
  subscription_id                   = "${var.subscription_id}"
  tenant_id                         = "${var.tenant_id}"
  vm_size                           = "Standard_DS2_v2"
}

build {
  sources = ["source.azure-arm.autogenerated_1"]

  provisioner "shell" {
    execute_command = "chmod +x {{ .Path }}; {{ .Vars }} sudo -E sh '{{ .Path }}'"
    inline          = ["apt-get update",
    "apt-get upgrade -y",
    "apt-get install -y qemu-kvm virt-top libvirt-bin",
    "mkdir -p /var/kvm/images",
    "apt-get install -y virtinst",
    "/usr/sbin/waagent -force -deprovision+user && export HISTSIZE=0 && sync"
    ]
    inline_shebang  = "/bin/sh -x"
  }

}